### ISSUE TITLE
Exception Errors in Chapter 4: Could be newbie error as well

### ISSUE THREAD

**Issue by RustyKettle** [maxpumperla/learning_ray#3]
I'm going through this book and running the code as I go. I am running into the following issue:

`ALL DONE
Exception ignored in: <function RolloutWorker.__del__ at 0x7fb2260368c0>
Traceback (most recent call last):
  File "/home/rustykettle/.local/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 461, in _resume_span
TypeError: 'NoneType' object is not callable`

The ALL DONE is my print: 
```
ray.init()
gymEnv = GymEnvironment()
trainer = DQNTrainer(env=GymEnvironment, config={"num_workers": 4})  # <1>
config = trainer.get_config()  # <2>
#print(pretty_print(config))

for i in range(10):
    result = trainer.train()  # <3>

ray.shutdown()
print(pretty_print(result))  # <4>
print("ALL DONE")
```

It is to show that the exception is something to do with Ray, but it also might have something to do with my configuration. I followed the book very closely, but I'm not discounting a user-error on my part. 
[output.log](https://github.com/maxpumperla/learning_ray/files/9387304/output.log)

I'm also getting depreciation warnings that don't appear in the log. I'm imagining that this happens because it is happening on a different thread.

**Comment by RustyKettle** [comment]
Another quick observation. This doesn't happen when running via the cmd_line using the yml method, so it further points to something acting up in my script.

**Comment by RustyKettle** [comment]
More observations. It still happens with the multiagent example, and when updating to Ray 2,0.

**Comment by maxpumperla** [comment]
hey @RustyKettle, by now we've rewritten a substantial part of this chapter due to lots of API changes. I ran the examples locally and on colab and so far don't see any problems. Closing this issue for now, but please feel free to reopen if your problems persist!
