### ISSUE TITLE
May I translate your book to chinese version?

### ISSUE THREAD

**Issue by sepilqi** [maxpumperla/learning_ray#8]
Who am I?
* 7+ years in Technical Writing in chinese.
* 8+ years Experience in AI Infrastructure, AI/ML.

I read early release of Learning Ray. I love your book, and I am looking forward to sharing it with others.
May I contribute chinese transilation to this awsome book?

**Comment by maxpumperla** [comment]
@sepilqi apologies for not seeing your message earlier! I'd be psyched to see a Chinese translation for the book for sure. The "problem" is that O'Reilly has the rights to the book, so as author I can't decide this.

I could try to get you in touch with the publisher. What do you think?

**Comment by sepilqi** [comment]
Wow that will be great, I am looking forward to getting in touch with the publisher @maxpumperla

**Comment by maxpumperla** [comment]
@sepilqi can you write me an email (it's in my profile)?

**Comment by maxpumperla** [comment]
p.s. publishers are usually a little hesitant with translations before having any market validation on how well the book sells. just so that you're mentally prepared for a longer journey.

in any case, thanks so much for your offer!

**Comment by sepilqi** [comment]
@maxpumperla I will send you email in several days later

**Comment by maxpumperla** [comment]
awesome, looking forward to it @sepilqi. Closing this issue for now.
